export const ALLOWANCE_CREATE_REQUEST = "ALLOWANCE_CREATE_REQUEST";
export const ALLOWANCE_CREATE_SUCCESS = "ALLOWANCE_CREATE_SUCCESS";
export const ALLOWANCE_CREATE_FAIL = "ALLOWANCE_CREATE_FAIL";
export const ALLOWANCE_CREATE_RESET = "ALLOWANCE_CREATE_RESET";

export const ALLOWANCE_DELETE_REQUEST = "ALLOWANCE_DELETE_REQUEST";
export const ALLOWANCE_DELETE_SUCCESS = "ALLOWANCE_DELETE_SUCCESS";
export const ALLOWANCE_DELETE_FAIL = "ALLOWANCE_DELETE_FAIL";

export const ALLOWANCE_DETAILS_REQUEST = "ALLOWANCE_DETAILS_REQUEST";
export const ALLOWANCE_DETAILS_SUCCESS = "ALLOWANCE_DETAILS_SUCCESS";
export const ALLOWANCE_DETAILS_FAIL = "ALLOWANCE_DETAILS_FAIL";

export const ALLOWANCE_UPDATE_REQUEST = "ALLOWANCE_UPDATE_REQUEST";
export const ALLOWANCE_UPDATE_SUCCESS = "ALLOWANCE_UPDATE_SUCCESS";
export const ALLOWANCE_UPDATE_FAIL = "ALLOWANCE_UPDATE_FAIL";

export const ALLOWANCE_LIST_REQUEST = "ALLOWANCE_LIST_REQUEST";
export const ALLOWANCE_LIST_SUCCESS = "ALLOWANCE_LIST_SUCCESS";
export const ALLOWANCE_LIST_FAIL = "ALLOWANCE_LIST_FAIL";
export const ALLOWANCE_LIST_RESET = "ALLOWANCE_LIST_RESET";
