export const BANK_DETAILS_CREATE_REQUEST = "BANK_DETAILS_CREATE_REQUEST";
export const BANK_DETAILS_CREATE_SUCCESS = "BANK_DETAILS_CREATE_SUCCESS";
export const BANK_DETAILS_CREATE_FAIL = "BANK_DETAILS_CREATE_FAIL";

export const BANK_DETAILS_REQUEST = "BANK_DETAILS_REQUEST";
export const BANK_DETAILS_SUCCESS = "BANK_DETAILS_SUCCESS";
export const BANK_DETAILS_FAIL = "BANK_DETAILS_FAIL";

export const BANK_UPDATE_REQUEST = "BANK_UPDATE_REQUEST";
export const BANK_UPDATE_SUCCESS = "BANK_UPDATE_SUCCESS";
export const BANK_UPDATE_FAIL = "BANK_UPDATE_FAIL";
