export const DEDUCTION_CREATE_REQUEST = "DEDUCTION_CREATE_REQUEST";
export const DEDUCTION_CREATE_SUCCESS = "DEDUCTION_CREATE_SUCCESS";
export const DEDUCTION_CREATE_FAIL = "DEDUCTION_CREATE_FAIL";
export const DEDUCTION_CREATE_RESET = "DEDUCTION_CREATE_RESET";

export const DEDUCTION_DETAILS_REQUEST = "DEDUCTION_DETAILS_REQUEST";
export const DEDUCTION_DETAILS_SUCCESS = "DEDUCTION_DETAILS_SUCCESS";
export const DEDUCTION_DETAILS_FAIL = "DEDUCTION_DETAILS_FAIL";

export const DEDUCTION_UPDATE_REQUEST = "DEDUCTION_UPDATE_REQUEST";
export const DEDUCTION_UPDATE_SUCCESS = "DEDUCTION_UPDATE_SUCCESS";
export const DEDUCTION_UPDATE_FAIL = "DEDUCTION_UPDATE_FAIL";

export const DEDUCTION_LIST_REQUEST = "DEDUCTION_LIST_REQUEST";
export const DEDUCTION_LIST_SUCCESS = "DEDUCTION_LIST_SUCCESS";
export const DEDUCTION_LIST_FAIL = "DEDUCTION_LIST_FAIL";
export const DEDUCTION_LIST_RESET = "DEDUCTION_LIST_RESET";

export const DEDUCTION_DELETE_REQUEST = "DEDUCTION_DELETE_REQUEST";
export const DEDUCTION_DELETE_SUCCESS = "DEDUCTION_DELETE_SUCCESS";
export const DEDUCTION_DELETE_FAIL = "DEDUCTION_DELETE_FAIL";
