export const DESIGNATION_CREATE_REQUEST = "DESIGNATION_CREATE_REQUEST";
export const DESIGNATION_CREATE_SUCCESS = "DESIGNATION_CREATE_SUCCESS";
export const DESIGNATION_CREATE_FAIL = "DESIGNATION_CREATE_FAIL";
export const DESIGNATION_CREATE_RESET = "DESIGNATION_CREATE_RESET";

export const DESIGNATION_DETAILS_REQUEST = "DESIGNATION_DETAILS_REQUEST";
export const DESIGNATION_DETAILS_SUCCESS = "DESIGNATION_DETAILS_SUCCESS";
export const DESIGNATION_DETAILS_FAIL = "DESIGNATION_DETAILS_FAIL";

export const DESIGNATION_LIST_REQUEST = "DESIGNATION_LIST_REQUEST";
export const DESIGNATION_LIST_SUCCESS = "DESIGNATION_LIST_SUCCESS";
export const DESIGNATION_LIST_FAIL = "DESIGNATION_LIST_FAIL";
export const DESIGNATION_LIST_RESET = "DESIGNATION_LIST_RESET";

export const DESIGNATION_DELETE_REQUEST = "DESIGNATION_DELETE_REQUEST";
export const DESIGNATION_DELETE_SUCCESS = "DESIGNATION_DELETE_SUCCESS";
export const DESIGNATION_DELETE_FAIL = "DESIGNATION_DELETE_FAIL";

export const DESIGNATION_UPDATE_REQUEST = "DESIGNATION_UPDATE_REQUEST";
export const DESIGNATION_UPDATE_SUCCESS = "DESIGNATION_UPDATE_SUCCESS";
export const DESIGNATION_UPDATE_FAIL = "DESIGNATION_UPDATE_FAIL";
