export const EMPLOYEE_DEDUCTION_CREATE_REQUEST =
	"EMPLOYEE_DEDUCTION_CREATE_REQUEST";
export const EMPLOYEE_DEDUCTION_CREATE_SUCCESS =
	"EMPLOYEE_DEDUCTION_CREATE_SUCCESS";
export const EMPLOYEE_DEDUCTION_CREATE_FAIL = "EMPLOYEE_DEDUCTION_CREATE_FAIL";

export const EMPLOYEE_DEDUCTION_DETAILS_REQUEST =
	"EMPLOYEE_DEDUCTION_DETAILS_REQUEST";
export const EMPLOYEE_DEDUCTION_DETAILS_SUCCESS =
	"EMPLOYEE_DEDUCTION_DETAILS_SUCCESS";
export const EMPLOYEE_DEDUCTION_DETAILS_FAIL =
	"EMPLOYEE_DEDUCTION_DETAILS_FAIL";

export const EMPLOYEE_DEDUCTION_LIST_REQUEST =
	"EMPLOYEE_DEDUCTION_LIST_REQUEST";
export const EMPLOYEE_DEDUCTION_LIST_SUCCESS =
	"EMPLOYEE_DEDUCTION_LIST_SUCCESS";
export const EMPLOYEE_DEDUCTION_LIST_FAIL = "EMPLOYEE_DEDUCTION_LIST_FAIL";
export const EMPLOYEE_DEDUCTION_LIST_RESET = "EMPLOYEE_DEDUCTION_LIST_RESET";

export const EMPLOYEE_DEDUCTION_DELETE_REQUEST =
	"EMPLOYEE_DEDUCTION_DELETE_REQUEST";
export const EMPLOYEE_DEDUCTION_DELETE_SUCCESS =
	"EMPLOYEE_DEDUCTION_DELETE_SUCCESS";
export const EMPLOYEE_DEDUCTION_DELETE_FAIL = "EMPLOYEE_DEDUCTION_DELETE_FAIL";
export const EMPLOYEE_DEDUCTION_UPDATE_REQUEST =
	"EMPLOYEE_DEDUCTION_UPDATE_REQUEST";
export const EMPLOYEE_DEDUCTION_UPDATE_SUCCESS =
	"EMPLOYEE_DEDUCTION_UPDATE_SUCCESS";
export const EMPLOYEE_DEDUCTION_UPDATE_FAIL = "EMPLOYEE_DEDUCTION_UPDATE_FAIL";
