export const EMPLOYEE_ALLOWANCE_CREATE_REQUEST =
	"EMPLOYEE_ALLOWANCE_CREATE_REQUEST";
export const EMPLOYEE_ALLOWANCE_CREATE_SUCCESS =
	"EMPLOYEE_ALLOWANCE_CREATE_SUCCESS";
export const EMPLOYEE_ALLOWANCE_CREATE_FAIL = "EMPLOYEE_ALLOWANCE_CREATE_FAIL";
export const EMPLOYEE_ALLOWANCE_CREATE_RESET =
	"EMPLOYEE_ALLOWANCE_CREATE_RESET";

export const EMPLOYEE_ALLOWANCE_DELETE_REQUEST =
	"EMPLOYEE_ALLOWANCE_DELETE_REQUEST";
export const EMPLOYEE_ALLOWANCE_DELETE_SUCCESS =
	"EMPLOYEE_ALLOWANCE_DELETE_SUCCESS";
export const EMPLOYEE_ALLOWANCE_DELETE_FAIL = "EMPLOYEE_ALLOWANCE_DELETE_FAIL";

export const EMPLOYEE_ALLOWANCE_DETAILS_REQUEST =
	"EMPLOYEE_ALLOWANCE_DETAILS_REQUEST";
export const EMPLOYEE_ALLOWANCE_DETAILS_SUCCESS =
	"EMPLOYEE_ALLOWANCE_DETAILS_SUCCESS";
export const EMPLOYEE_ALLOWANCE_DETAILS_FAIL =
	"EMPLOYEE_ALLOWANCE_DETAILS_FAIL";

export const EMPLOYEE_ALLOWANCE_LIST_REQUEST =
	"EMPLOYEE_ALLOWANCE_LIST_REQUEST";
export const EMPLOYEE_ALLOWANCE_LIST_SUCCESS =
	"EMPLOYEE_ALLOWANCE_LIST_SUCCESS";
export const EMPLOYEE_ALLOWANCE_LIST_FAIL = "EMPLOYEE_ALLOWANCE_LIST_FAIL";
export const EMPLOYEE_ALLOWANCE_LIST_RESET = "EMPLOYEE_ALLOWANCE_LIST_RESET";

export const EMPLOYEE_ALLOWANCE_UPDATE_REQUEST =
	"EMPLOYEE_ALLOWANCE_UPDATE_REQUEST";
export const EMPLOYEE_ALLOWANCE_UPDATE_SUCCESS =
	"EMPLOYEE_ALLOWANCE_UPDATE_SUCCESS";
export const EMPLOYEE_ALLOWANCE_UPDATE_FAIL = "EMPLOYEE_ALLOWANCE_UPDATE_FAIL";
