export const PAYROLL_CREATE_REQUEST = "PAYROLL_CREATE_REQUEST";
export const PAYROLL_CREATE_SUCCESS = "PAYROLL_CREATE_SUCCESS";
export const PAYROLL_CREATE_FAIL = "PAYROLL_CREATE_FAIL";
export const PAYROLL_CREATE_RESET = "PAYROLL_CREATE_RESET";

export const PAYROLL_DETAILS_REQUEST = "PAYROLL_DETAILS_REQUEST";
export const PAYROLL_DETAILS_SUCCESS = "PAYROLL_DETAILS_SUCCESS";
export const PAYROLL_DETAILS_FAIL = "PAYROLL_DETAILS_FAIL";

export const PAYROLL_UPDATE_REQUEST = "PAYROLL_UPDATE_REQUEST";
export const PAYROLL_UPDATE_SUCCESS = "PAYROLL_UPDATE_SUCCESS";
export const PAYROLL_UPDATE_FAIL = "PAYROLL_UPDATE_FAIL";
export const PAYROLL_UPDATE_RESET = "PAYROLL_UPDATE_RESET";

export const PAYROLL_LIST_REQUEST = "PAYROLL_LIST_REQUEST";
export const PAYROLL_LIST_SUCCESS = "PAYROLL_LIST_SUCCESS";
export const PAYROLL_LIST_FAIL = "PAYROLL_LIST_FAIL";
export const PAYROLL_LIST_RESET = "PAYROLL_LIST_RESET";

export const PAYROLL_DELETE_REQUEST = "PAYROLL_DELETE_REQUEST";
export const PAYROLL_DELETE_SUCCESS = "PAYROLL_DELETE_SUCCESS";
export const PAYROLL_DELETE_FAIL = "PAYROLL_DELETE_FAIL";
