export const SCALE_CREATE_REQUEST = "SCALE_CREATE_REQUEST";
export const SCALE_CREATE_SUCCESS = "SCALE_CREATE_SUCCESS";
export const SCALE_CREATE_FAIL = "SCALE_CREATE_FAIL";
export const SCALE_CREATE_RESET = "SCALE_CREATE_RESET";

export const SCALE_DETAILS_REQUEST = "SCALE_DETAILS_REQUEST";
export const SCALE_DETAILS_SUCCESS = "SCALE_DETAILS_SUCCESS";
export const SCALE_DETAILS_FAIL = "SCALE_DETAILS_FAIL";

export const SCALE_LIST_REQUEST = "SCALE_LIST_REQUEST";
export const SCALE_LIST_SUCCESS = "SCALE_LIST_SUCCESS";
export const SCALE_LIST_FAIL = "SCALE_LIST_FAIL";
export const SCALE_LIST_RESET = "SCALE_LIST_RESET";

export const SCALE_DELETE_REQUEST = "SCALE_DELETE_REQUEST";
export const SCALE_DELETE_SUCCESS = "SCALE_DELETE_SUCCESS";
export const SCALE_DELETE_FAIL = "SCALE_DELETE_FAIL";

export const SCALE_UPDATE_REQUEST = "SCALE_UPDATE_REQUEST";
export const SCALE_UPDATE_SUCCESS = "SCALE_UPDATE_SUCCESS";
export const SCALE_UPDATE_FAIL = "SCALE_UPDATE_FAIL";
